[bugfix] continue db initialization even when module-initialization fails due to class dependancy errors (NoClassDefFoundError)
svn path=/trunk/eXist/; revision=8192