Repaired unwanted dependency with org.apache.commons.pool.PoolableObjectFactory (caused NoClassDefFoundError for OxygenXml). Errors are ignored (and logged)
svn path=/trunk/eXist/; revision=5674


Former-commit-id: c7ec48b8d3ea9a1c2c06d0885f3dec2e787939b9