[bugfix] continue db initialization even when module-initialization fails due to class dependancy errors (NoClassDefFoundError)
svn path=/trunk/eXist/; revision=8192


Former-commit-id: 30123337310f6453501cc48a07eb616a29145cfa