Changed testLargeAttributeSimple() so that it creates a document with twice the same big attribute. Fails when the attributes' size is 513, saying: expected:<2> but was:<0>
svn path=/trunk/eXist-1.0/; revision=551


Former-commit-id: 69b8fdc805bb34449e0add94432b1ea217b7761c